get('/dgmap/app/interface/townStreetCleanIndex|2.10镇街洁净指数接口')
get('/dgmap/app/interface/caseConcernsHigh?timeStr=&townName=|2.16市民关注案件高发类型分类统计接口')
get('/dgmap/app/interface/collectionCaseHigh?timeStr=&townName=|2.17自行采集类案件高发案件类型统计接口')
get('/dgmap/app/interface/caseConcerns?timeStr=&townName=|2.1市民关注案件分类统计接口（已废弃）')
get('/dgmap/app/interface/collectionCase?timeStr=&townName=|2.2自行采集案件分类统计接口(已废弃)')
get('/dgmap/app/interface/getCaseMetrics|2.8案件指标接口')
get('/dgmap/app/interface/highCaseTypeWarn?timeStr=&townName=|2.9高发案件类型预警统计接口')
get('/dgmap/app/interface/thermal/perCapitaWasteWarn?timeStr=|1.10人均垃圾超标预警接口')
get('/dgmap/app/interface/highIncidenceCaseWarn?timeStr=|1.11区域案件高发预警接口')
get('/dgmap/app/interface/thermal/furnaceTemperatureDetail?name=|1.13热电厂炉温情况详情接口')
get('/dgmap/app/interface/thermal/gasEmissionDetail?name=|1.14热电厂气体排放详情接口')
get('/dgmap/app/interface/thermal/wasteIncinerationWarn?timeStr=|1.15热电厂垃圾焚烧情况预警')
get('/dgmap/app/interface/thermal/factoryRubbishWeight?timeStr=|1.16热电厂接收的垃圾量接口')
get('/dgmap/app/interface/outTimeCase?townName=|1.1智慧城管超时案件统计接口（已废弃）')
get('/dgmap/app/interface/wasteIncinerationWarn?townName=|1.2垃圾焚烧预警统计接口')
get('/dgmap/app/interface/cityscapeSanitation?timeStr=|1.3市容环卫模块统计接口')
get('/dgmap/app/interface/wisdomCityManagement?townName=|1.4智慧城管模块统计接口')
get('/dgmap/app/interface/urbanManagement?townName=|1.5城管执法统计接口')
get('/dgmap/app/interface/thermal/wasteIncinerationExcess?timeStr=&townName=|1.9镇街垃圾焚烧合同超标预警接口')
get('/dgmap/app/interface/outTimeCaseMonth?townName=|2.18智慧城管月度超时案件接口')
get('/dgmap/app/interface/restroom/getRestroomData?townName=|1.12公厕资源接口')
get('/dgmap/app/interface/todayCaseTown|1.6（未使用，基本废弃）首页 - table')
get('/dgmap/app/interface/getMapDotData?type=|1.8首页 - 地图所有')
get('/dgmap/app/interface/getCaseMetricsAllTown?timeStr=|2.15 （重要）各镇街案件指标')
get('/dgmap/app/interface/townCaseNum?timeStr=|2.19城管 - 人均案件数量热力图')
get('/dgmap/app/interface/wisdomCityManagementSearch?timeStr=|2.5智慧城管 - 右侧table')
